source ~/.vim/plugin-ctrl/ycm.vim
source ~/.vim/plugin-ctrl/fzf.vim
"source ~/.vim/plugin-ctrl/syntastic.vim
"source ~/.vim/plugin-ctrl/py-syntax.vim
source ~/.vim/plugin-ctrl/airline.vim
source ~/.vim/plugin-ctrl/ale.vim
source ~/.vim/plugin-ctrl/py-mode.vim
source ~/.vim/plugin-ctrl/autoformat.vim
source ~/.vim/plugin-ctrl/ultisnips.vim
